[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/videos/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.mov"
  [headers.values]
    Content-Type = "video/quicktime"
    Access-Control-Allow-Origin = "*" 